dist: trusty
sudo: require
language: cpp
compiler: gcc
os: 
    - linux
    - osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.x
    packages:
      - cmake
      - cmake-data
      - gcc-7
      - g++-7
      - libglu1-mesa-dev
      - xorg-dev
script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CC=/usr/bin/gcc-7; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX=/usr/bin/g++-7; fi
    - gcc -v && g++ -v && cmake --version
    - git --version
    - pip install --user conan
    - conan user
    - conan install -b
    - cmake -Bbuild -H.
    - cmake --build build
    - cd build && ctest
